### ISSUE TITLE
Edit metadata locally

### ISSUE THREAD

**Issue by jurra** [ITC-CRIB/JupyterFAIR#11]
# Story
I want to edit metadata locally with my favourite text editor/IDE so that I can create and update it easily.

## Given that
- The user can edit metadata in someway in the working environment (minimum a text editor with yaml)
- When a new request from the working environment/commandline or gui is created, the metadata created is passed as input to create the new record.

## Some requirements and considerations
- The metadata needs to be validated against the standard before making the request
- We are sticking to a basic standard, something like Dublin core (Business rule)

## Implementation ideas
- Metadata is created in yaml by the user
- It is transformed to xml. [Package example](https://pypi.org/project/xml-json-yaml-convert/)
- Then using some validator against schema. [XMLschema package](https://xmlschema.readthedocs.io/en/latest/intro.html)
- Then this is passed as a body request to the api.

Any ideas or issues? This raises other issues such as downloading and getting the latest version, with the yml format for instace...

**Comment by manuGil** [comment]
This was implemented in the fairly package
