### ISSUE TITLE
Create a data record from working environment

### ISSUE THREAD

**Issue by jurra** [ITC-CRIB/JupyterFAIR#12]
# Story
I want to create a metadata record directly from my working environment so that I can perform the task without leaving my working environment. 

## Given that
- A user is logged in a server or jupyter-lab server or console
- When user sends a request using a command (either via console or some gui)
- Then the application checks for the validity of the record
- Then the request is sent
- Then the server/data provider returns a link where the record and the item lives. So that the user can also check it
- Then confirmation that request was succesful

## Some requirements and considerations
- See #11. The user needs to create a record via either a text editor or some kind of form extension in jupyter lab. 
- It would be nice to use some generic protocol, instead of specific API

## Implementation ideas 
1. Basic option: Do this via 4TU API
2. Do a wrapper class that has an interface with different implementations for the same repository. These idea can be explored using the Open API swagger code generator for those repositories that are compatible the [Open API specification](https://swagger.io/specification/).
3. Find a common protocol in the spirit of SWORD and OAI-PMH

**Comment by jurra** [comment]
This one is partially done, we have the wrapper class.
Swagger generates a big library/package we havent incorporate it into our project, an important reason is that the autogeneration using figshare reference is buggy and incomplete. 
The wrapper class allows to implement deposition and uploading by any means, it can be SWORD as well.

**Comment by manuGil** [comment]
This was implemented in the fairly package
