### ISSUE TITLE
Specify which data files and folders to upload as a dataset

### ISSUE THREAD

**Issue by jurra** [ITC-CRIB/JupyterFAIR#14]
# Story
I want to specify which data files and folders are included in the dataset so that I can manage the dataset easily

## Given that
- A user has a working environment (local or remote) with files and folders that she doesn't want to archive to the data repository.

## Some requirements and considerations
- The user shall specify in advance which files or folders to include in the data archiving process.
- The user shall provide a list of files and folders to include or exclude from the data archiving process.
- A user might need to specify a different list for different data repositories. 

## Implementation ideas 
- The user can provide a list of files and folders to include as a YAML/plain text file (a manifest) which the application can use to upload datasets to a data repository.

**Comment by manuGil** [comment]
This was implemented in the fairly package
