### ISSUE TITLE
Discussion on GUI design for the JupyterLab extension

### ISSUE THREAD

**Issue by manuGil** [ITC-CRIB/JupyterFAIR#45]
- How should users interact with the JupyterFAIR extension via a GUI?
- What the GUI for the JupyterFAIR extension should look like?
- Can we use some of the [GUI helpers from JupyterLab](https://jupyterlab.readthedocs.io/en/stable/extension/ui_helpers.html)?
- Should we use the [lumino library](https://github.com/jupyterlab/lumino) instead for building a custom GUI?

**Comment by manuGil** [comment]
Hello @girgink  and @jurra 
These are the first mock-ups of the GUI for the JupyterLab extension. Please take a look and comment. https://hackmd.io/@oAZuk0Z1R4mP1zAX7pM_VA/HkUXquQMj

**Comment by jurra** [comment]
Hi @manuGil it looks reasonable to me what you are suggesting. I am assuming this is the most straightforward approach reusing the lumino library, is this the case?

**Comment by manuGil** [comment]
Hey @jurra , That's what I understand from Lumino; however, how I will find out how straightforward the implementation will be.  I will keep an eye open for the need to simplify the GUI due to time constraints.
